name: Deploying specified version for preview

on:
  workflow_call:

jobs:
  deploy_application:
   runs-on: ubuntu-latest
   steps:
      - name: Make repo name variable compliant with K8 namespace rules
        run: echo "reponame=$(echo ${{ github.event.repository.name }} | tr _ - )" >> $GITHUB_ENV
      - name: Checkout Pipeline repository
        uses: actions/checkout@v3
        with:
          repository: wgall/cloudrun_laravel_cicd
          token: ${{ secrets.CLOUDRUN_GIT_TOKEN }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5
          terraform_wrapper: false
      - name: Authenitcate pipeline repository 
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.SA_CREDENTIALS }}
      - name: Setup pipline repository
        uses: google-github-actions/setup-gcloud@main 
        with:
          project_id: labs-370214
          export_default_credentials: true 
      - name: Deploy application  
        working-directory: ./versioning
        env:
          tag: ${{ github.event.release.tag_name }}
        run: |
          version=$(echo ${{ env.tag }} | tr . -)
          terraform init 
          terraform apply --auto-approve -var "image=${{env.reponame}}" -var "tag=${{env.tag}}" -var "project=${{env.reponame}}-$version"
           gcloud compute url-maps add-path-matcher test --path-matcher-name=${{env.reponame}}-$version --default-service=https://www.googleapis.com/compute/v1/projects/labs-370214/global/backendServices/${{ env.reponame }}-$version --new-hosts="${{env.reponame}}-$version.gallit.net"
